name: bsl-plataforma-2
region: atl
services:
  - name: bsl-plataforma2
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: dtalero78/BSL-PLATAFORMA2
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    source_dir: /
